### ISSUE TITLE
deseq2-init.R returned non-zero exit status 1.

### ISSUE THREAD

**Issue by sateeshperi** [snakemake-workflows/rna-seq-star-deseq2#10] opened 2018-10-15 22:50 UTC
```
[Mon Oct 15 15:42:46 2018]
rule deseq2_init:
    input: counts/all.tsv
    output: deseq2/all.rds
    log: logs/deseq2/init.log
    jobid: 3

Activating conda environment: /media/leochong/backup4/rna-seq-star-deseq2/.snakemake/conda/28f98caa
[Mon Oct 15 15:43:01 2018]
Error in rule deseq2_init:
    jobid: 3
    output: deseq2/all.rds
    log: logs/deseq2/init.log
    conda-env: /media/leochong/backup4/rna-seq-star-deseq2/.snakemake/conda/28f98caa

RuleException:
CalledProcessError in line 33 of /media/leochong/backup4/rna-seq-star-deseq2/rules/diffexp.smk:
Command 'source activate /media/leochong/backup4/rna-seq-star-deseq2/.snakemake/conda/28f98caa; set -euo pipefail;  Rscript /media/leochong/backup4/rna-seq-star-deseq2/.snakemake/scripts/tmpju9bqzqy.deseq2-init.R ' returned non-zero exit status 1.
  File "/media/leochong/backup4/rna-seq-star-deseq2/rules/diffexp.smk", line 33, in __rule_deseq2_init
  File "/home/leochong/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```
Any input on why the pipeline is failing?

**Comment by johanneskoester** [comment] 2018-10-25 15:36
You should check the log file that is mentioned in the error message.

**Comment by johanneskoester** [comment] 2018-11-12 10:55
Can you post your samples.tsv and the file counts/all.tsv?

**Comment by sateeshperi** [comment] 2018-11-15 16:05
@johanneskoester PFA my samples.tsv and counts/all.tsv
[samples_counts_all.zip](https://github.com/snakemake-workflows/rna-seq-star-deseq2/files/2586079/samples_counts_all.zip)

**Comment by johanneskoester** [comment] 2018-11-15 16:14
Mhm, looks correct. Maybe a bug in DESeq. I suggest to debug a bit the R script that fails. In particular, I would suggest to print `cts` and `coldata`. Maybe you can post that afterwards.

**Comment by mikelove** [comment] 2019-02-13 21:28
The error is being called from SummarizedExperiment. You cannot construct a SE where the column names of the matrix and the rownames of the colData are inconsistent. Here you have:

```
cts <- read.table(snakemake@input[["counts"]], header=TRUE, row.names="gene")
coldata <- read.table(snakemake@params[["samples"]], header=TRUE, row.names="sample")
```

If you want to get around SE's check here, you can drop the colnames of `cts`, that is go with the `assay colnames() must be NULL` option.

**Comment by sateeshperi** [comment] 2019-02-13 21:51
Thanks @mikelove

**Comment by johanneskoester** [comment] 2019-02-15 13:49
Wait, is this really solved now? So, to me rows and cols look the same. Why are they inconsistent?

**Comment by sateeshperi** [comment] 2019-02-15 19:47
Hmm I see, maybe @mikelove can comment on that.

Meanwhile, I am testing by dropping the colnames. Will update on this asap.

**Comment by mikelove** [comment] 2019-02-15 20:31
They look consistent in R? You can be sure that SummarizedExperiment is doing an x == y comparison and throwing an error if these two character vectors are not equal.

**Comment by johanneskoester** [comment] 2019-02-18 08:52
Good point, could be caused by some hidden whitespace for example. Let's see what @sateeshperi finds out.

**Comment by sateeshperi** [comment] 2019-02-19 06:03
```
Error in .validate_names(colnames, ans_colnames, "assay colnames()", "colData rownames()") : 
  assay colnames() must be NULL or identical to colData rownames()
Calls: DESeqDataSetFromMatrix ... SummarizedExperiment -> SummarizedExperiment -> .local -> .validate_names
Execution halted
````

**Comment by sateeshperi** [comment] 2019-02-19 06:04
[counts_samples.zip](https://github.com/snakemake-workflows/rna-seq-star-deseq2/files/2878535/counts_samples.zip)

**Comment by sateeshperi** [comment] 2019-02-20 22:09
@johanneskoester @mikelove I think i found the bug. 
```
> colnames(cts)
[1] "Index.33L_CP_C1" "Index.33L_CP_C2" "Index.33L_CP_C3" "Index.36L_CP_V1" "Index.36L_CP_V2" "Index.36L_CP_V3"
> rownames(coldata)
[1] "Index-31L_CP_C1" "Index-32L_CP_C2" "Index-33L_CP_C3" "Index-34L_CP_V1" "Index-35L_CP_V2" "Index-36L_CP_V3"
```
The counts file "all.tsv" has the name of the samples being replaced from "-" to "."

**Comment by johanneskoester** [comment] 2019-03-04 09:25
@sateeshperi good point. I forgot about the implicit replacement in column names with R.  A fix will come together with PR #12.

**Comment by johanneskoester** [comment] 2019-03-04 11:29
Should be fixed now in the master branch. @sateeshperi can you confirm?

**Closed by johanneskoester** 2019-03-04 11:29 UTC

**Comment by sateeshperi** [comment] 2019-03-09 21:59
@johanneskoester Yes ! .....that fixes it :+1:

**Comment by qins** [comment] 2021-04-13 02:18
In case someone get error:

> Error in .validate_names(colnames, ans_colnames, "assay colnames()", "colData rownames()") : 
>     assay colnames() must be NULL or identical to colData rownames()
> Calls: DESeqDataSetFromMatrix ... SummarizedExperiment -> SummarizedExperiment -> .local -> .validate_names
> Execution halted

Solution:
`colnames(countDataDF) <- NULL`

countDataDF is the input dataframe of countData parameter.
